name: Update README

on:
  push:
    paths:
      - 'Leetcode/**'

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README
        run: |
          python update_readme.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update README.md"
          file_pattern: README.md
